[package]
name = "rovo-macros"
version.workspace = true
edition.workspace = true
description = "Proc macros for rovo - OpenAPI documentation for axum"
license.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
proc-macro2 = "1.0"
syn = "2.0"
